spring:
  application:
    name: admin-server

server:
  port: 8090
  address: 0.0.0.0

# Configuración de Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-hostname: true
    hostname: admin-server
    lease-timeout-in-seconds: 20
    lease-renewal-interval-in-seconds: 10

# Configuración de Spring Boot Admin
spring.boot.admin:
  discovery:
    enabled: true
    converter:
      management-context-path: /actuator
  ui:
    title: "Microservices Admin Dashboard"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
